Dev1
ewilson/chirpr pull request #6
Opened 2016-09-23 00:11 UTC by dmitchelldm74

2016-09-24 13:23 UTC, ewilson requested changes
Functionality mainly looks good, with a few issues:
- It is not obvious how to find users to follow. Could you make a link that takes you to a page that displays all users -- like what I see if I click the search button with nothing in the field?

<img width="484" alt="screen shot 2016-09-24 at 9 19 44 am" src="https://cloud.githubusercontent.com/assets/385580/18808731/2d74a2fa-8238-11e6-8a10-1e3891e89b83.png">

Here I would like to be able to click anywhere in the bar, not just on the name.

2016-09-24 13:23 UTC, ewilson commented on chirpr.py
> +from flask import Flask, request, g, render_template, redirect, url_for, flash, session, Response
Do you use the `Response`? I don't find it when I search this page.

2016-09-24 13:23 UTC, ewilson commented on chirpr.py
> +        user = db_access.get_user(uid)[0]
Does `get_user` return a list? That's not the way it should be. Since only one user can exist for an id, this should just return the user itself.

Please change `db_access.get_user` and be careful to fix other places where it is called.

2016-09-24 13:23 UTC, ewilson commented on chirpr.py
> +        message = 'danger;Sorry, you cannot follow %s.' % (user)
You should consider (Flashing with categories)[http://flask.pocoo.org/docs/0.11/patterns/flashing/#flashing-with-categories] instead of this semicolon delimited stuff.

Also, this message is a bit odd. If you have a better explanation of why the user can't be followed, use that. If this is a catch-all, then maybe it should be more like 'An error has occurred'

2016-09-24 13:23 UTC, ewilson commented on chirpr.py
> +    return following
Could you explain what you are doing here? It is called `get_followers` but it returns `following`.

If I understood it better, it might be a not-too-difficult SQL query.

2016-09-24 13:23 UTC, ewilson commented on chirpr.py
> +    return render_template('follow.html', to_follow=db_access.to_follow(), following=following, get_user=db_access.get_user)
I notice that you are passing the function `db_access.get_user` rather than calling the function. 

Please do all of the preparation of data on the in the python code, making DB calls from the templates is bound to get too tangled up.

2016-09-24 13:23 UTC, ewilson commented on data/migrations/02_add_followers.sql
> +CREATE TABLE followers (handleid integer, followerid integer);
For naming you variables and DB columns, `handle_id` is much more typical. Minor point, but things get hard to read if you mash everything together.

2016-09-24 13:23 UTC, ewilson commented on db_access.py
> +    return False
This seems backwards. If I want to follow the user with `id=5`, and my `id=2`, and you call `follow(2,5)`, then we have an entry in the `followers` table with `(2, 5)` -- which makes it look like `5` is following me.

I think this explains why other things seem backward in other places. You need the `uid` to go in the `followerid` column here.

2016-09-24 13:23 UTC, ewilson commented on db_access.py
> +    return conn.execute('SELECT handleid FROM followers WHERE followerid=?', (uid,)).fetchall()
This would be turned around if you modify your `follow` method as I suggested.

2016-09-24 13:23 UTC, ewilson commented on db_access.py
> +    for i in conn.execute('SELECT handleid, followerid FROM followers').fetchall(): #.fetchmany()
Get rid of `#.fetchmany()`

2016-09-24 13:23 UTC, ewilson commented on db_access.py
> +    return followers
Please use some comments, this would be much easier to read if I understood what the goal was. The name `to_follow` is pretty general, so if forces me to work harder to understand.

`i` is not a good name for a row returned from a DB query.  And then reassigning your iteration variable several times, this is really crazy.

If you have questions, ask again in Slack, I'll get to them when I can.

2016-09-24 13:23 UTC, ewilson commented on db_access.py
> +    return followers
Similarly, iterating and reassigning `i` in the middle of the loop is too much, there is a better way.

2016-09-24 23:00 UTC, dmitchelldm74 commented on chirpr.py
> +from flask import Flask, request, g, render_template, redirect, url_for, flash, session, Response
Response is for testing purposes only, should it be removed?

2016-09-26 22:34 UTC, ewilson commented on chirpr.py
> +from flask import Flask, request, g, render_template, redirect, url_for, flash, session, Response
I'm curious how you are using it. You can keep it for now, but we might be able to find a better way to test.

2016-09-27 01:36 UTC, dmitchelldm74 commented on chirpr.py
> +from flask import Flask, request, g, render_template, redirect, url_for, flash, session, Response
`return Response(template('search.html'), 'text/plain')`

2016-09-29 01:40 UTC, dmitchelldm74 commented on data/migrations/02_add_followers.sql
> +CREATE TABLE followers (handleid integer, followerid integer);
I changed `followerid` to `follower_id`

2016-09-30 12:07 UTC, ewilson approved these changes

2016-09-30 12:09 UTC, merged